# Generated by Django 2.2.1 on 2020-02-28 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ICD', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('code', models.CharField(db_column='code', max_length=20, primary_key=True, serialize=False)),
                ('description', models.TextField(db_column='description')),
                ('parent', models.CharField(db_column='parent', max_length=20)),
                ('children', models.CharField(db_column='children', max_length=1000)),
                ('times_coded', models.IntegerField(db_column='times_coded', default=0)),
                ('times_coded_dad', models.IntegerField(db_column='times_coded_dad', default=0)),
                ('keyword_terms', models.TextField(db_column='keyword_terms')),
                ('selectable', models.BooleanField(db_column='selectable', default=True)),
            ],
        ),
    ]
