# Generated by Django 2.2.1 on 2020-02-14 16:53

from django.conf import settings
import django.contrib.postgres.fields.jsonb
import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion
from django.contrib.postgres.operations import BtreeGinExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        BtreeGinExtension(),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sessionId', models.CharField(max_length=48)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'annotations',
            },
        ),
        migrations.AddIndex(
            model_name='annotation',
            index=django.contrib.postgres.indexes.GinIndex(fields=['user', 'data', 'updated', 'sessionId'], name='annotation_gin'),
        ),
    ]
