# Generated by Django 2.2.1 on 2019-12-17 22:03

from django.db import migrations
from django.contrib.postgres.operations import BtreeGinExtension


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0003_auto_20191217_2200'),
    ]

    operations = [
        BtreeGinExtension(),
    ]
