# Generated by Django 2.2.1 on 2019-12-18 18:38

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0004_auto_20191217_2203'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='annotation',
            name='user_time_idx',
        ),
        migrations.RemoveIndex(
            model_name='annotation',
            name='data_gin',
        ),
        migrations.AddIndex(
            model_name='annotation',
            index=django.contrib.postgres.indexes.GinIndex(fields=['user', 'data', 'updated'], name='user_data_timestamp_gin'),
        ),
    ]
