# Generated by Django 2.2.1 on 2019-12-18 22:39

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0005_auto_20191218_1838'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='annotation',
            name='user_data_timestamp_gin',
        ),
        migrations.AddField(
            model_name='annotation',
            name='sessionId',
            field=models.CharField(default=0, max_length=12, unique=True),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='annotation',
            index=django.contrib.postgres.indexes.GinIndex(fields=['user', 'data', 'updated', 'sessionId'], name='annotation_gin'),
        ),
    ]
